dist: focal
sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libgtk-3-dev
      - libxdo-dev

rust:
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo --verify
  - ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/lib-*

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
